// Tous les textes de l'interface, en français et en anglais.
// Les entrées dynamiques (avec un nom, un nombre…) sont des fonctions.
export const STRINGS = {
  fr: {
    common: {
      titleSuffix: '· Réservation en ligne',
      defaultSalonName: 'Votre salon',
      footer: 'Démo portfolio · données enregistrées sur cet appareil uniquement',
      save: 'Enregistrer',
      langLabel: 'Français / English',
    },
    ui: {
      close: 'Fermer',
      back: 'Retour',
    },
    nav: {
      myBookings: 'Mes RDV',
      pro: 'Pro',
      proAria: 'Espace commerçant',
      clientView: 'Vue client',
      lockAria: 'Verrouiller',
    },
    steps: {
      labels: ['Prestation', 'Coiffeur', 'Créneau', 'Coordonnées'],
      prevAria: 'Étape précédente',
      aria: (n) => `Étape ${n} sur 4`,
    },
    errors: {
      name: 'Indiquez votre nom et prénom.',
      phone: 'Numéro invalide (ex. 06 12 34 56 78).',
      email: 'Adresse e-mail invalide.',
    },
    hero: {
      eyebrow: 'Réservation en ligne',
      subtitle: 'Choisissez votre prestation, votre coiffeur et votre créneau en moins d’une minute.',
    },
    booking: {
      chooseService: 'Choisissez une prestation',
      withWhom: 'Avec qui ?',
      anyStaff: 'Peu importe',
      firstAvailable: 'Le premier coiffeur disponible',
      notReady: {
        title: 'Réservations bientôt ouvertes',
        text: 'Le salon n’a pas encore publié ses prestations. Revenez très vite !',
        link: 'Je suis le commerçant : configurer',
      },
      confirm: {
        cancelledTitle: 'Rendez-vous annulé',
        confirmedTitle: 'C’est réservé !',
        cancelledText: 'Le créneau a été libéré.',
        greeting: (first, salon) => `Merci ${first}, ${salon} vous attend.`,
        emailSending: (email) => `Envoi de la confirmation à ${email}…`,
        emailSent: (email) => `Confirmation envoyée à ${email}`,
        emailError: 'L’e-mail n’a pas pu partir. Votre rendez-vous est bien enregistré.',
        emailDisabled: 'Démo : l’envoi d’e-mail n’est pas activé, cette page fait foi.',
        addToCalendar: 'Ajouter à mon agenda',
        another: 'Prendre un autre rendez-vous',
        cancelThis: 'Annuler ce rendez-vous',
      },
      cancelDialog: {
        title: 'Annuler le rendez-vous ?',
        text: 'Le créneau sera libéré et proposé à d’autres clients.',
        confirm: 'Oui, annuler',
      },
      notifyCancelled: 'Rendez-vous annulé',
    },
    slot: {
      when: 'Quand souhaitez-vous venir ?',
      conflict: 'Ce créneau vient d’être réservé par quelqu’un d’autre. Choisissez-en un autre.',
      daysAria: 'Jours',
      today: 'auj.',
      full: 'complet',
      closed: 'fermé',
      none: {
        title: 'Aucun créneau disponible',
        text: 'Tout est complet sur la période ouverte à la réservation. Essayez un autre coiffeur ou revenez plus tard.',
      },
      morning: 'Matin',
      afternoon: 'Après-midi',
      continue: (time) => `Continuer · ${time}`,
    },
    contact: {
      title: 'Vos coordonnées',
      name: 'Nom et prénom',
      phone: 'Téléphone',
      email: 'E-mail',
      emailHint: 'Pour recevoir votre confirmation.',
      namePlaceholder: 'Camille Martin',
      phonePlaceholder: '06 12 34 56 78',
      emailPlaceholder: 'camille@exemple.fr',
      submit: 'Confirmer le rendez-vous',
      footnote: 'Vos informations servent uniquement à ce rendez-vous.',
    },
    myBookings: {
      title: 'Mes rendez-vous',
      empty: { title: 'Aucun rendez-vous', text: 'Les rendez-vous pris depuis cet appareil apparaîtront ici.' },
      bookNow: 'Réserver maintenant',
      upcoming: 'À venir',
      cancelledLabel: (byPro) => (byPro ? 'Annulé par le salon' : 'Annulé'),
      calendar: 'Agenda',
      cancel: 'Annuler',
      past: 'Passés',
    },
    pro: {
      tabs: { planning: 'Planning', services: 'Prestations', team: 'Équipe', hours: 'Horaires', settings: 'Réglages' },
      brandSub: 'Espace commerçant',
      sectionsAria: 'Sections',
    },
    pin: {
      backAria: 'Retour à la vue client',
      eyebrow: 'Espace commerçant',
      enterAria: (n) => `${n} chiffres saisis`,
      wrong: 'Code incorrect',
      enter: 'Saisissez votre code',
      eraseAria: 'Effacer',
      demo: (pin) => `Code de démonstration : ${pin}`,
    },
    planning: {
      setupTitle: 'Ouvrez vos réservations en 3 étapes',
      step1: 'Ajouter vos prestations',
      step2: 'Ajouter vos coiffeurs et leurs prestations',
      step3: 'Vérifier vos horaires d’ouverture',
      day: 'Jour',
      week: 'Semaine',
      prevAria: 'Précédent',
      nextAria: 'Suivant',
      backToday: 'Revenir à aujourd’hui',
      todayLabel: (date) => `Aujourd’hui · ${date}`,
      weekLabel: (d1, d2) => `Semaine du ${d1} au ${d2}`,
      all: 'Tous',
      statAppts: 'rendez-vous',
      statRevenue: 'chiffre prévu',
      statCancelled: 'annulé',
      statCancelledPlural: 'annulés',
      rdvCount: (n) => `${n} RDV`,
      closed: 'Fermé',
      cancelDialog: {
        title: 'Annuler ce rendez-vous ?',
        text: (name, service, time, phone) => `${name} · ${service} à ${time}. Pensez à prévenir le client au ${phone}.`,
        confirm: 'Annuler le rendez-vous',
      },
      notifyCancelled: 'Rendez-vous annulé, créneau libéré',
      dayEmpty: { closed: 'Salon fermé ce jour-là', none: 'Aucun rendez-vous', text: 'Les réservations de vos clients apparaîtront ici.' },
      cancelledBy: (byPro) => (byPro ? 'Annulé par le salon' : 'Annulé par le client'),
      cancelBtn: 'Annuler',
    },
    services: {
      notifySaved: 'Prestation enregistrée',
      notifyDeleted: 'Prestation supprimée',
      title: 'Prestations',
      add: 'Ajouter',
      empty: { title: 'Aucune prestation', text: 'Ajoutez ce que vous proposez, avec sa durée et son prix.', add: 'Ajouter une prestation' },
      noStaffWarn: 'aucun coiffeur : invisible pour les clients',
      editAria: (name) => `Modifier ${name}`,
      deleteAria: (name) => `Supprimer ${name}`,
      deleteDialog: { title: 'Supprimer la prestation ?', text: (name) => `« ${name} » ne sera plus proposée. Les rendez-vous déjà pris sont conservés.`, confirm: 'Supprimer' },
      newTitle: 'Nouvelle prestation',
      editTitle: 'Modifier la prestation',
      nameLabel: 'Nom',
      durationLabel: 'Durée (min)',
      priceLabel: 'Prix (€)',
      errName: 'Donnez un nom à la prestation.',
      errDuration: 'Durée en minutes, entre 5 et 600.',
      errPrice: 'Prix en euros (0 accepté).',
      doneBy: 'Réalisée par',
    },
    team: {
      notifySaved: 'Coiffeur enregistré',
      notifyRemoved: 'Coiffeur retiré',
      title: 'Équipe',
      add: 'Ajouter',
      tip: 'Astuce : créez d’abord vos prestations pour pouvoir les attribuer.',
      tipLink: 'Aller aux prestations',
      empty: { title: 'Aucun coiffeur', text: 'Ajoutez les membres de votre équipe et cochez les prestations que chacun réalise.', add: 'Ajouter un coiffeur' },
      noServiceWarn: 'aucune prestation cochée',
      editAria: (name) => `Modifier ${name}`,
      removeAria: (name) => `Retirer ${name}`,
      deleteDialog: {
        title: (name) => `Retirer ${name} ?`,
        textUpcoming: (n) => `${n} rendez-vous à venir restent visibles dans le planning ; pensez à les annuler ou à prévenir les clients.`,
        textSimple: 'Il ne sera plus proposé aux clients.',
        confirm: 'Retirer',
      },
      newTitle: 'Nouveau coiffeur',
      editTitle: 'Modifier le coiffeur',
      nameLabel: 'Prénom',
      errName: 'Indiquez un prénom.',
      servicesLegend: 'Prestations réalisées',
    },
    hours: {
      errNoRange: 'Ajoutez au moins une plage ou fermez ce jour.',
      errOrder: 'L’heure de fin doit suivre l’heure de début.',
      errOverlap: 'Deux plages se chevauchent.',
      title: 'Horaires d’ouverture',
      lead: 'Communs à toute l’équipe. Les rendez-vous déjà pris ne sont pas modifiés.',
      open: 'Ouvert',
      closed: 'Fermé',
      startAria: 'Début',
      endAria: 'Fin',
      removeRangeAria: 'Retirer la plage',
      addRange: 'Ajouter une plage',
      fixErrors: 'Corrigez les horaires en rouge',
      saveBtn: 'Enregistrer les horaires',
      notifySaved: 'Horaires enregistrés',
    },
    settings: {
      title: 'Réglages',
      salonPanel: 'Salon',
      salonNameLabel: 'Nom affiché aux clients',
      salonNameHint: 'Vide = « Votre salon ».',
      salonNamePlaceholder: 'Votre salon',
      notifyNameSaved: 'Nom enregistré',
      rulesPanel: 'Règles de réservation',
      horizonLabel: 'Réservation possible jusqu’à',
      horizonOption: (d) => `${d} jours à l’avance${d === 30 ? ' (1 mois)' : ''}`,
      notifyHorizonSaved: 'Horizon enregistré',
      bufferLabel: 'Battement entre deux rendez-vous',
      bufferHint: 'Temps de préparation ajouté après chaque rendez-vous d’un coiffeur.',
      bufferOption: (b) => (b ? `${b} minutes` : 'Aucun'),
      notifyBufferSaved: 'Battement enregistré',
      rulesNote: 'Délai minimum : réservation au plus tard 2 heures avant le rendez-vous. Créneaux enchaînés selon la durée de la prestation.',
      pinPanel: 'Code d’accès',
      pinLabel: 'Nouveau code (4 chiffres)',
      pinHint: 'Protection de démonstration, sans vraie sécurité.',
      change: 'Changer',
      notifyPinChanged: 'Code modifié',
      emailPanel: 'E-mail de confirmation',
      emailOn: 'Activé : chaque client reçoit un e-mail (via EmailJS).',
      emailOff: 'Non configuré : confirmation à l’écran et fichier agenda seulement.',
      demoPanel: 'Données de démonstration',
      demoText: 'Tout est enregistré dans ce navigateur uniquement. La réinitialisation efface prestations, équipe, rendez-vous et réglages.',
      resetBtn: 'Réinitialiser la démo',
      resetDialog: { title: 'Tout réinitialiser ?', text: 'L’application reviendra à son état de départ. Cette action est définitive.', confirm: 'Réinitialiser' },
      notifyReset: 'Démo réinitialisée',
    },
  },
  en: {
    common: {
      titleSuffix: '· Online booking',
      defaultSalonName: 'Your salon',
      footer: 'Portfolio demo · data stored on this device only',
      save: 'Save',
      langLabel: 'Français / English',
    },
    ui: {
      close: 'Close',
      back: 'Back',
    },
    nav: {
      myBookings: 'My bookings',
      pro: 'Pro',
      proAria: 'Business area',
      clientView: 'Client view',
      lockAria: 'Lock',
    },
    steps: {
      labels: ['Service', 'Staff', 'Time slot', 'Details'],
      prevAria: 'Previous step',
      aria: (n) => `Step ${n} of 4`,
    },
    errors: {
      name: 'Enter your first and last name.',
      phone: 'Invalid number (e.g. 07123 456789).',
      email: 'Invalid email address.',
    },
    hero: {
      eyebrow: 'Online booking',
      subtitle: 'Choose your service, your stylist and your time slot in under a minute.',
    },
    booking: {
      chooseService: 'Choose a service',
      withWhom: 'With whom?',
      anyStaff: 'No preference',
      firstAvailable: 'The first available stylist',
      notReady: {
        title: 'Bookings opening soon',
        text: 'The salon hasn’t published its services yet. Check back very soon!',
        link: 'I’m the business owner: set up',
      },
      confirm: {
        cancelledTitle: 'Appointment cancelled',
        confirmedTitle: 'You’re booked!',
        cancelledText: 'The time slot has been released.',
        greeting: (first, salon) => `Thanks ${first}, ${salon} looks forward to seeing you.`,
        emailSending: (email) => `Sending confirmation to ${email}…`,
        emailSent: (email) => `Confirmation sent to ${email}`,
        emailError: 'The email could not be sent. Your appointment is still confirmed.',
        emailDisabled: 'Demo: email sending isn’t enabled, this page is your confirmation.',
        addToCalendar: 'Add to my calendar',
        another: 'Book another appointment',
        cancelThis: 'Cancel this appointment',
      },
      cancelDialog: {
        title: 'Cancel the appointment?',
        text: 'The time slot will be released and offered to other clients.',
        confirm: 'Yes, cancel',
      },
      notifyCancelled: 'Appointment cancelled',
    },
    slot: {
      when: 'When would you like to come?',
      conflict: 'This time slot was just booked by someone else. Please choose another one.',
      daysAria: 'Days',
      today: 'today',
      full: 'full',
      closed: 'closed',
      none: {
        title: 'No time slot available',
        text: 'Everything is fully booked for the period open to booking. Try another stylist or check back later.',
      },
      morning: 'Morning',
      afternoon: 'Afternoon',
      continue: (time) => `Continue · ${time}`,
    },
    contact: {
      title: 'Your details',
      name: 'Full name',
      phone: 'Phone',
      email: 'Email',
      emailHint: 'To receive your confirmation.',
      namePlaceholder: 'Jane Smith',
      phonePlaceholder: '07123 456789',
      emailPlaceholder: 'jane@example.com',
      submit: 'Confirm appointment',
      footnote: 'Your details are only used for this appointment.',
    },
    myBookings: {
      title: 'My appointments',
      empty: { title: 'No appointments', text: 'Appointments booked from this device will appear here.' },
      bookNow: 'Book now',
      upcoming: 'Upcoming',
      cancelledLabel: (byPro) => (byPro ? 'Cancelled by the salon' : 'Cancelled'),
      calendar: 'Calendar',
      cancel: 'Cancel',
      past: 'Past',
    },
    pro: {
      tabs: { planning: 'Schedule', services: 'Services', team: 'Team', hours: 'Hours', settings: 'Settings' },
      brandSub: 'Business area',
      sectionsAria: 'Sections',
    },
    pin: {
      backAria: 'Back to client view',
      eyebrow: 'Business area',
      enterAria: (n) => `${n} digits entered`,
      wrong: 'Incorrect code',
      enter: 'Enter your code',
      eraseAria: 'Erase',
      demo: (pin) => `Demo code: ${pin}`,
    },
    planning: {
      setupTitle: 'Open your bookings in 3 steps',
      step1: 'Add your services',
      step2: 'Add your stylists and their services',
      step3: 'Check your opening hours',
      day: 'Day',
      week: 'Week',
      prevAria: 'Previous',
      nextAria: 'Next',
      backToday: 'Back to today',
      todayLabel: (date) => `Today · ${date}`,
      weekLabel: (d1, d2) => `Week of ${d1} to ${d2}`,
      all: 'All',
      statAppts: 'appointments',
      statRevenue: 'expected revenue',
      statCancelled: 'cancelled',
      statCancelledPlural: 'cancelled',
      rdvCount: (n) => `${n} appt${n === 1 ? '' : 's'}`,
      closed: 'Closed',
      cancelDialog: {
        title: 'Cancel this appointment?',
        text: (name, service, time, phone) => `${name} · ${service} at ${time}. Remember to notify the client at ${phone}.`,
        confirm: 'Cancel appointment',
      },
      notifyCancelled: 'Appointment cancelled, time slot released',
      dayEmpty: { closed: 'Salon closed that day', none: 'No appointments', text: 'Your clients’ bookings will appear here.' },
      cancelledBy: (byPro) => (byPro ? 'Cancelled by the salon' : 'Cancelled by the client'),
      cancelBtn: 'Cancel',
    },
    services: {
      notifySaved: 'Service saved',
      notifyDeleted: 'Service deleted',
      title: 'Services',
      add: 'Add',
      empty: { title: 'No services', text: 'Add what you offer, with its duration and price.', add: 'Add a service' },
      noStaffWarn: 'no stylist assigned: hidden from clients',
      editAria: (name) => `Edit ${name}`,
      deleteAria: (name) => `Delete ${name}`,
      deleteDialog: { title: 'Delete this service?', text: (name) => `“${name}” will no longer be offered. Existing appointments are kept.`, confirm: 'Delete' },
      newTitle: 'New service',
      editTitle: 'Edit service',
      nameLabel: 'Name',
      durationLabel: 'Duration (min)',
      priceLabel: 'Price (€)',
      errName: 'Give the service a name.',
      errDuration: 'Duration in minutes, between 5 and 600.',
      errPrice: 'Price in euros (0 accepted).',
      doneBy: 'Performed by',
    },
    team: {
      notifySaved: 'Stylist saved',
      notifyRemoved: 'Stylist removed',
      title: 'Team',
      add: 'Add',
      tip: 'Tip: create your services first so you can assign them.',
      tipLink: 'Go to services',
      empty: { title: 'No stylists', text: 'Add your team members and tick the services each one performs.', add: 'Add a stylist' },
      noServiceWarn: 'no service selected',
      editAria: (name) => `Edit ${name}`,
      removeAria: (name) => `Remove ${name}`,
      deleteDialog: {
        title: (name) => `Remove ${name}?`,
        textUpcoming: (n) => `${n} upcoming appointment${n === 1 ? '' : 's'} remain visible in the schedule; remember to cancel them or notify clients.`,
        textSimple: 'They will no longer be offered to clients.',
        confirm: 'Remove',
      },
      newTitle: 'New stylist',
      editTitle: 'Edit stylist',
      nameLabel: 'First name',
      errName: 'Enter a first name.',
      servicesLegend: 'Services performed',
    },
    hours: {
      errNoRange: 'Add at least one time range or close this day.',
      errOrder: 'The end time must be after the start time.',
      errOverlap: 'Two time ranges overlap.',
      title: 'Opening hours',
      lead: 'Shared by the whole team. Existing appointments are not changed.',
      open: 'Open',
      closed: 'Closed',
      startAria: 'Start',
      endAria: 'End',
      removeRangeAria: 'Remove range',
      addRange: 'Add a range',
      fixErrors: 'Fix the hours shown in red',
      saveBtn: 'Save hours',
      notifySaved: 'Hours saved',
    },
    settings: {
      title: 'Settings',
      salonPanel: 'Salon',
      salonNameLabel: 'Name shown to clients',
      salonNameHint: 'Empty = “Your salon”.',
      salonNamePlaceholder: 'Your salon',
      notifyNameSaved: 'Name saved',
      rulesPanel: 'Booking rules',
      horizonLabel: 'Bookable up to',
      horizonOption: (d) => `${d} days ahead${d === 30 ? ' (1 month)' : ''}`,
      notifyHorizonSaved: 'Booking window saved',
      bufferLabel: 'Buffer between appointments',
      bufferHint: 'Preparation time added after each stylist’s appointment.',
      bufferOption: (b) => (b ? `${b} minutes` : 'None'),
      notifyBufferSaved: 'Buffer saved',
      rulesNote: 'Minimum notice: bookings close 2 hours before the appointment. Time slots follow on from each other based on the service duration.',
      pinPanel: 'Access code',
      pinLabel: 'New code (4 digits)',
      pinHint: 'Demo protection only, not real security.',
      change: 'Change',
      notifyPinChanged: 'Code changed',
      emailPanel: 'Confirmation email',
      emailOn: 'Enabled: every client receives an email (via EmailJS).',
      emailOff: 'Not configured: on-screen confirmation and calendar file only.',
      demoPanel: 'Demo data',
      demoText: 'Everything is stored in this browser only. Resetting erases services, team, appointments and settings.',
      resetBtn: 'Reset the demo',
      resetDialog: { title: 'Reset everything?', text: 'The app will return to its starting state. This action is permanent.', confirm: 'Reset' },
      notifyReset: 'Demo reset',
    },
  },
}
